project:
  type: website
  output-dir: docs

format:
  html:
    theme: 
      light: cosmo
    mainfont: Poppins
    headingfont: Montserrat
    css: styles.scss
    toc: true
    page-layout: full

website:
  title: "Melannie Moreno"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      - href: posts.qmd
        text: Portfolio
    right:
      - icon: github
        href: https://github.com/mmorenorolon/mmorenorolon.github.io

  page-footer:
    left: "Copyright 2025, Melannie Moreno"
    right:
      - href: posts.qmd
        text: Posts
