<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Melannie Moreno Rolón">
<meta name="dcterms.date" content="2025-12-13">
<meta name="description" content="Analysis of U.S. West Coast Exclusive Economic Zones to identify suitable marine aquaculture areas based on species-specific sea surface temperature and depth ranges.">

<title>Evaluating Species-Specific Environmental Suitability for Marine Aquaculture Development Along the U.S. West Coast – Melannie Moreno Rolón</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



<link rel="stylesheet" href="../../styles.scss">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Melannie Moreno Rolón</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html"> 
<span class="menu-text">Blog Posts</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mmorenorolon/mmorenorolon.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <div class="quarto-title-block"><div><h1 class="title">Evaluating Species-Specific Environmental Suitability for Marine Aquaculture Development Along the U.S. West Coast</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
                  <div>
        <div class="description">
          Analysis of U.S. West Coast Exclusive Economic Zones to identify suitable marine aquaculture areas based on species-specific sea surface temperature and depth ranges.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">MEDS</div>
                <div class="quarto-category">R</div>
                <div class="quarto-category">Geospatial Analysis</div>
              </div>
                  </div>
  </div>
    
  <div class="quarto-title-meta-author column-page-left">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://mmorenorolon.github.io/">Melannie Moreno Rolón</a> </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              <a href="https://ucsb-meds.github.io/">
              Master of Environmental Data Science Program @ The Bren School (UCSB)
              </a>
            </p>
        </div>
    </div>

  <div class="quarto-title-meta column-page-left">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 13, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#sea-surface-temperature-processing" id="toc-sea-surface-temperature-processing" class="nav-link" data-scroll-target="#sea-surface-temperature-processing">1. Sea Surface Temperature Processing</a></li>
  <li><a href="#bathymetry-processing" id="toc-bathymetry-processing" class="nav-link" data-scroll-target="#bathymetry-processing">2. Bathymetry Processing</a></li>
  <li><a href="#environmental-suitability-classification" id="toc-environmental-suitability-classification" class="nav-link" data-scroll-target="#environmental-suitability-classification">3. Environmental Suitability Classification</a></li>
  <li><a href="#suitability-estimation-at-the-eez-level" id="toc-suitability-estimation-at-the-eez-level" class="nav-link" data-scroll-target="#suitability-estimation-at-the-eez-level">4. Suitability Estimation at the EEZ Level</a></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#oyster-aquaculture-suitability" id="toc-oyster-aquaculture-suitability" class="nav-link" data-scroll-target="#oyster-aquaculture-suitability">Oyster Aquaculture Suitability</a></li>
  <li><a href="#scallop-aquaculture-suitability" id="toc-scallop-aquaculture-suitability" class="nav-link" data-scroll-target="#scallop-aquaculture-suitability">Scallop Aquaculture Suitability</a></li>
  <li><a href="#eez-level-suitable-area-summary" id="toc-eez-level-suitable-area-summary" class="nav-link" data-scroll-target="#eez-level-suitable-area-summary">EEZ-Level Suitable Area Summary</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#data-citations" id="toc-data-citations" class="nav-link" data-scroll-target="#data-citations">Data Citations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://cf-images.us-east-1.prod.boltdns.net/v1/static/659677166001/7d188fff-3e5e-4059-b7ef-ffd4be742900/fef50dd1-d58f-4a03-84f7-579058fa9fd7/1280x720/match/image.jpg" class="img-fluid figure-img" width="450"></p>
<figcaption>Aquaculture Image Sourced from NOAA Fisheries</figcaption>
</figure>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: import-libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#|code-fold: true</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Import libraries</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(testthat)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>As the global population continues to rise, so does the pressure on wild fisheries to meet growing seafood demand. Marine aquaculture offers a promising solution, providing a sustainable alternative that can relieve pressure on wild stocks while supporting economic development. According to Gentry et al.&nbsp;(2017), the availability of suitable ocean space is unlikely to limit the expansion of marine aquaculture, indicating that many regions have the physical capacity to support future growth. This presents an important opportunity for countries such as the United States to develop aquaculture systems that meet both economic and environmental objectives. Thus, the central objective of this project is to identify which areas along the U.S. West Coast meet the environmental conditions necessary to support sustainable aquaculture development.</p>
<p>Identifying where aquaculture can be responsibly developed requires evaluating the environmental conditions that support healthy growth and minimize ecological impacts. This project assesses the suitability of West Coast Exclusive Economic Zones (EEZs), defined as marine areas extending up to 200 nautical miles from the U.S. coastline where the United States has jurisdiction over natural resource use (NOAA, 2024), for marine aquaculture using two key environmental constraints: sea surface temperature (SST) and bathymetry. Using satellite-derived SST data from 2008–2012 and a regional bathymetry dataset, the total area within each EEZ that meets species-specific environmental thresholds can be quantified. The analysis focuses on two groups: oysters, which are already widely cultivated in California, and the Purple Hinged Rock Scallop (<em>Crassadoma gigantea</em>), a giant scallop species with emerging aquaculture potential (Culver et al., 2022). By integrating spatial environmental data with habitat requirements, this project identifies where conditions are most favorable for expanding sustainable marine aquaculture along the U.S. West Coast.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p>To assess aquaculture suitability along the U.S. West Coast, a generalized function was implemented that automates the processing of sea surface temperature (SST), bathymetry, and EEZ boundary data. Depth requirements for the purple-hinged rock scallop (<em>Crassadoma gigantea</em>) were obtained from SeaLifeBase, which reports an ecological depth range of 0–80 m below sea level (b.s.l.) (University of British Columbia, 2025; Harbo, 1997). Thermal tolerance data for this species are not provided in SeaLifeBase, so temperature thresholds were derived from Reef Life Survey observations, which indicate a temperature range of approximately 13.3–22.1 degrees Celsius (Schmid, 2025). In addition, suitability thresholds for oysters were incorporated based on published ecological ranges, with optimal SST values between 11–30 degrees Celsius and depth values between 0 and 70 meters b.s.l. These values were used to define species-specific suitability thresholds for reclassification of SST and bathymetry data. The workflow consisted of four phases.</p>
<section id="sea-surface-temperature-processing" class="level2">
<h2 class="anchored" data-anchor-id="sea-surface-temperature-processing">1. Sea Surface Temperature Processing</h2>
<p>Daily 5-km SST averages from 2008–2012 were compiled and converted into a single long-term mean SST raster. The datasets were first stacked and then averaged by pixel. SST values, originally in Kelvin, were converted to degrees Celsius.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and process SST</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>SST_2008 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2008.tif'</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>SST_2009 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2009.tif'</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>SST_2010 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2010.tif'</span>))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>SST_2011 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2011.tif'</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>SST_2012 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2012.tif'</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that all SST rasters share the same CRS</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">crs</span>(SST_2008) <span class="sc">==</span> <span class="fu">crs</span>(SST_2009) <span class="sc">&amp;</span> </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">crs</span>(SST_2009) <span class="sc">==</span> <span class="fu">crs</span>(SST_2010) <span class="sc">&amp;</span> </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">crs</span>(SST_2010) <span class="sc">==</span> <span class="fu">crs</span>(SST_2011)<span class="sc">&amp;</span> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">crs</span>(SST_2011) <span class="sc">==</span> <span class="fu">crs</span>(SST_2012)) {</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"All coordinate reference systems match!"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Coordinate reference systems do not match!"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Stack SST rasters (2008–2012)</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>sst_stack <span class="ot">&lt;-</span> <span class="fu">c</span>(SST_2008, SST_2009, SST_2010, SST_2011, SST_2012)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that rasters were stacked successfully</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">nlyr</span>(sst_stack) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>     <span class="fu">message</span>(<span class="st">"SST stack failed: no raster layers detected."</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>     <span class="fu">stop</span>(<span class="st">"Halting execution."</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute mean SST over time (per pixel)</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>mean_sst <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">mean</span>(sst_stack)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert temperature units from Kelvin to Celsius</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>mean_sst_c <span class="ot">&lt;-</span> mean_sst <span class="sc">-</span> <span class="fl">273.15</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="bathymetry-processing" class="level2">
<h2 class="anchored" data-anchor-id="bathymetry-processing">2. Bathymetry Processing</h2>
<p>A regional depth raster was reprojected to match the SST coordinate reference system (CRS). The bathymetry was cropped to the spatial extent of the SST data and resampled to its resolution to maintain consistency and cell alignment between rasters.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare bathymetry (depth) raster</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Load the bathymetry raster</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>bathy <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"depth.tif"</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Make CRS match SST:</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>bathy_proj <span class="ot">&lt;-</span> <span class="fu">project</span>(bathy, <span class="fu">crs</span>(mean_sst_c))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that the re-projection of the depth raster was successful</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Bathymetry CRS matches SST CRS after projection"</span>, {</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_identical</span>(<span class="fu">crs</span>(bathy_proj), <span class="fu">crs</span>(mean_sst_c))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Crop bathymetry to SST's extent</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>bathy_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(bathy_proj, mean_sst_c)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Check resolution of depth vs sst data</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">xres</span>(bathy_crop) <span class="sc">==</span> <span class="fu">xres</span>(mean_sst_c) <span class="sc">&amp;</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">yres</span>(bathy_crop) <span class="sc">==</span> <span class="fu">yres</span>(mean_sst_c))) {</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"Raster resolutions match!"</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Raster resolutions do not match."</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Raster resolutions do not match.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resample bathymetry to SST resolution (so each cell lines up):</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>depth_res <span class="ot">&lt;-</span> <span class="fu">resample</span>(bathy_crop, mean_sst_c, <span class="at">method =</span> <span class="st">"near"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that the depth and SST match in resolution</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Depth raster was resampled to match SST resolution"</span>, {</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_equal</span>(<span class="fu">res</span>(depth_res), <span class="fu">res</span>(mean_sst_c))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="environmental-suitability-classification" class="level2">
<h2 class="anchored" data-anchor-id="environmental-suitability-classification">3. Environmental Suitability Classification</h2>
<p>Species-specific temperature and depth constraints were translated into binary suitability surfaces. For the purple-hinged rock scallop (<em>Crassadoma gigantea</em>), SST values between 13.3–22.1 Celsius and depths between 0–80 meters b.s.l. were classified as suitable (value = 1), with all other values set to unsuitable (value = 0). In contrast, for oysters, suitability was defined by a broader SST range of 11–30 degrees Celsius and shallower depths between 0 and 70 meters b.s.l. Separate binary rasters were generated for each species, and suitability layers were multiplied to produce combined indices identifying locations that simultaneously satisfied both environmental conditions.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reclassify SST into suitable / unsuitable</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The oyster thresholds for SST are between 11–30 Celsius</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>sst_rcl <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">11</span>,  <span class="dv">0</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">11</span>, <span class="dv">30</span>,  <span class="dv">1</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">30</span>, <span class="cn">Inf</span>, <span class="dv">0</span>), <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>sst_suit <span class="ot">&lt;-</span> <span class="fu">classify</span>(mean_sst_c, <span class="at">rcl =</span> sst_rcl)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Reclassify depth into suitable or unsuitable (1, 0)</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># The depth thresholds for oysters range is 0-70 meters b.s.l.</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>depth_rcl <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="dv">70</span>, <span class="dv">0</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">-</span><span class="dv">70</span>, <span class="dv">0</span>, <span class="dv">1</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">0</span>, <span class="cn">Inf</span>, <span class="dv">0</span>), <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>depth_suit <span class="ot">&lt;-</span> <span class="fu">classify</span>(depth_res, depth_rcl)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine SST and depth suitability</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Unit test for sst and depth CRS</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Reclassified rasters share identical CRS"</span>, {</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_identical</span>(<span class="fu">crs</span>(sst_suit), <span class="fu">crs</span>(depth_suit))</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiply to get 1 only where both are suitable</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>suitability <span class="ot">&lt;-</span> sst_suit <span class="sc">*</span> depth_suit <span class="co"># 1 = suitable, 0 = unsuitable</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="suitability-estimation-at-the-eez-level" class="level2">
<h2 class="anchored" data-anchor-id="suitability-estimation-at-the-eez-level">4. Suitability Estimation at the EEZ Level</h2>
<p>Exclusive Economic Zone (EEZ) boundaries were transformed to match the SST projection. The combined suitability raster was masked to the extent of each EEZ, and the area of each raster cell was computed in square kilometers. Suitable cell areas were aggregated within each EEZ to obtain total suitable area per region. These results were subsequently merged with the EEZ polygon dataset and visualized using a colorblind-friendly continuous color scale.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare EEZ vector and mask</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>eez_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"wc_regions_clean.shp"</span>), <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to SpatVector format</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>eez <span class="ot">&lt;-</span> <span class="fu">vect</span>(eez_sf)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-project with mean sst's CRS</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>eez_proj <span class="ot">&lt;-</span> <span class="fu">project</span>(eez, mean_sst_c)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that the re-projection of the EEZ shapefile was successful</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Bathymetry CRS matches SST CRS after projection"</span>, {</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_identical</span>(<span class="fu">crs</span>(eez_proj), <span class="fu">crs</span>(mean_sst_c))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Mask suitability by EEZ</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>suitability_eez <span class="ot">&lt;-</span> <span class="fu">mask</span>(suitability, eez_proj)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Count suitable cells per EEZ</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co"># a. Compute area in squared kilometers of each raster cell</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>cell_area_km <span class="ot">&lt;-</span> <span class="fu">cellSize</span>(suitability_eez, <span class="at">unit =</span> <span class="st">"km"</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a><span class="co"># b. Multiply suitability (0/1) by area to get "suitable area per cell"</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>suitable_area_raster <span class="ot">&lt;-</span> suitability_eez <span class="sc">*</span> cell_area_km</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Cells that were 1 now contain area in km²</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Cells that were 0 remain 0</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="co"># c. Extract total suitable area (km²) for each EEZ polygon</span></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>eez_suitable_area <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extract</span>(suitable_area_raster, </span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>                             eez_proj,</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>                             <span class="at">fun =</span> sum,</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>                             <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a><span class="co"># d. Add the EEZ region names to the output</span></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace "region" with the correct column name from your EEZ shapefile</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>eez_suitable_area<span class="sc">$</span>region <span class="ot">&lt;-</span> eez_proj<span class="sc">$</span>rgn</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the "mean"column</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(eez_suitable_area)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"suitable_km2"</span></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Format the table for EEZ suitable area totals</span></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>eez_suitable_area_table <span class="ot">&lt;-</span> eez_suitable_area <span class="sc">%&gt;%</span></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(region, suitable_km2) <span class="sc">%&gt;%</span></span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"EEZ Region"</span>, <span class="st">"Suitable Area (km²)"</span>),</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"Total Suitable Area by EEZ Region"</span>,</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>        <span class="at">align =</span> <span class="st">"lr"</span>, <span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge table back into EEZ SpatVector</span></span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>eez_map <span class="ot">&lt;-</span> eez_proj</span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>eez_map<span class="sc">$</span>suitable_km2 <span class="ot">&lt;-</span> eez_suitable_area<span class="sc">$</span>suitable_km2</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the final map</span></span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>map_final <span class="ot">&lt;-</span> <span class="fu">tm_basemap</span>(<span class="st">"Esri.OceanBasemap"</span>) <span class="sc">+</span></span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(eez_map) <span class="sc">+</span></span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"suitable_km2"</span>, </span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">values =</span> <span class="st">"brewer.blues"</span>, </span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">style =</span> <span class="st">"quantile"</span>),</span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">bg.color =</span> <span class="st">"white"</span>,</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">bg.alpha =</span> <span class="fl">0.2</span>,</span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">title =</span> <span class="st">"Suitable Area (km²)"</span>,</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"right"</span>, <span class="st">"top"</span>)),</span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a>              <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"rgn"</span>, <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb7-72"><a href="#cb7-72" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb7-73"><a href="#cb7-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb7-74"><a href="#cb7-74" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="st">"Suitable Area for Oyster Aquaculture in West Coast EEZ"</span>) <span class="sc">+</span></span>
<span id="cb7-75"><a href="#cb7-75" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-76"><a href="#cb7-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">TRUE</span>, <span class="at">frame.lwd =</span> <span class="fl">0.4</span>, <span class="at">frame.r =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb7-77"><a href="#cb7-77" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-78"><a href="#cb7-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scalebar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">250</span>, <span class="dv">500</span>), </span>
<span id="cb7-79"><a href="#cb7-79" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>)) <span class="sc">+</span></span>
<span id="cb7-80"><a href="#cb7-80" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-81"><a href="#cb7-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">"arrow"</span>, <span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"left"</span>, <span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb7-82"><a href="#cb7-82" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-83"><a href="#cb7-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tmap_options</span>(<span class="at">component.autoscale =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="data-analysis" class="level1">
<h1>Data Analysis</h1>
<p>The workflow was first applied to oysters to demonstrate the processing steps before generalizing the approach. To avoid repeating the oyster workflow for each species, we implemented a generalized function that accepts species-specific parameters.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: oyster-function</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"R"</span>,<span class="st">"suitability_function.R"</span>)) </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>oyster_results <span class="ot">&lt;-</span> <span class="fu">map_suitability</span>(<span class="at">tmin =</span> <span class="dv">11</span>, <span class="at">tmax =</span> <span class="dv">30</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">dmin =</span> <span class="sc">-</span><span class="dv">70</span>, <span class="at">dmax =</span> <span class="dv">0</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">species_name =</span> <span class="st">"Oysters"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>We then tested the function with scallop parameters to confirm that the function can be applied to any species of interest and their ecological parameters.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: scallop-function</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>scallop_results <span class="ot">&lt;-</span> <span class="fu">map_suitability</span>(<span class="at">tmin =</span> <span class="fl">13.3</span>, <span class="at">tmax =</span> <span class="fl">22.1</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dmin =</span> <span class="sc">-</span><span class="dv">80</span>, <span class="at">dmax =</span> <span class="dv">0</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">species_name =</span> <span class="st">"Purple-Hinged Rock Scallops"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>The resulting suitability maps and EEZ-level summaries for oysters and scallops are shown below.</p>
<section id="oyster-aquaculture-suitability" class="level2">
<h2 class="anchored" data-anchor-id="oyster-aquaculture-suitability">Oyster Aquaculture Suitability</h2>
<p><img src="../..\figures/oyster_map.png" class="img-fluid"></p>
</section>
<section id="scallop-aquaculture-suitability" class="level2">
<h2 class="anchored" data-anchor-id="scallop-aquaculture-suitability">Scallop Aquaculture Suitability</h2>
<p><img src="../..\figures/scallop_map.png" class="img-fluid"></p>
</section>
<section id="eez-level-suitable-area-summary" class="level2">
<h2 class="anchored" data-anchor-id="eez-level-suitable-area-summary">EEZ-Level Suitable Area Summary</h2>
<p>To support comparisons across regions, the total environmentally suitable area for aquaculture within each West Coast Exclusive Economic Zone (EEZ) is summarized in the figures below. These tables quantify how much space within each EEZ meets species-specific temperature and depth thresholds. With these metrics, aquaculture potential across regions and between species was compared.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Total Suitable Area for Oysters by EEZ Region</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">EEZ Region</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Suitable Area (km²)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Oregon</td>
<td style="text-align: right;">1074.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northern California</td>
<td style="text-align: right;">178.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Central California</td>
<td style="text-align: right;">4069.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southern California</td>
<td style="text-align: right;">3757.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">2378.3</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Total Suitable Area for Purple-Hinged Rock Scallops by EEZ Region</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">EEZ Region</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Suitable Area (km²)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Oregon</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northern California</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Central California</td>
<td style="text-align: right;">118.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southern California</td>
<td style="text-align: right;">3567.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">0.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The analysis identified stark differences in the amount of environmentally suitable area for aquaculture across West Coast EEZ regions. For oysters, Central California and Southern California contained the largest suitable areas, with approximately 4,070 squared km and 3,757 squared km respectively, followed by Washington (2,378 squared km) and Oregon (1,074 squared km). Northern California showed a more limited suitable habitat (178 squared km). In contrast, suitable areas for purple-hinged rock scallops were highly concentrated in the southern portion of the study region. Southern California accounted for nearly all suitable habitat (3,567 squared km), with a small area in Central California (119 km²), while Oregon, Washington, and Northern California contained no suitable area based on the species’ temperature and depth thresholds.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The results directly address the project objective of identifying where environmental conditions along the U.S. West Coast support sustainable marine aquaculture development. The spatial differences in aquaculture suitability among oysters and scallops reflect how environmental constraints, namely sea surface temperature and bathymetry, shape the feasibility of expanding aquaculture across Exclusive Economic Zones (EEZs).</p>
<p>Oyster suitability was broadly distributed across the West Coast, with the greatest concentrations being in Central and Southern California. These regions offer both the depth and thermal ranges that align with oyster tolerance, which resulted in several thousand square kilometers of potentially viable habitat. Washington and Oregon also contained meaningful amounts of suitable area, although to a lesser extent. The distribution pattern suggests that oyster aquaculture has relatively flexible environmental requirements within this coastline. This widespread distribution supports prior findings that physical ocean space is unlikely to limit aquaculture expansion (Gentry et al., 2017) and suggests that oysters represent a species with strong potential to contribute to meeting growing seafood demand while alleviating pressure on wild fisheries.</p>
<p>In contrast, the distribution of suitable habitat for purple-hinged rock scallops was highly geographically restricted. Southern California dominated the available area, as it contributed to nearly all suitable habitat identified in the study, with only a small area in Central California meeting threshold conditions. The absence of suitable areas in Oregon, Washington, and Northern California indicates that the species’ temperature range limits its potential along the cooler northern waters. These results align with the species’ known geographic distribution, as purple-hinged rock scallops are more frequently associated with subtidal, subtropical environments (Culver et al., 2022).</p>
<p>The stark contrast between the two species underscores the importance of evaluating on a species-specific level and considering their environmental thresholds when evaluating aquaculture potential. While oysters exhibit broad tolerance across the West Coast that enables aquaculture development across multiple EEZs, the purple-hinged rock scallop is limited to a much smaller geographic range despite being native to the region. From a planning perspective, this means that opportunities to expand scallop aquaculture are highly geographically concentrated, while oyster aquaculture can be distributed more widely. Further research is needed to translate these metrics into practical site selection, like evaluating regulatory conditions, ecological interactions, and infrastructure considerations. Nonetheless, by identifying where environmental conditions are most favorable, this study provides a necessary first step toward supporting sustainable marine aquaculture development along the U.S. West Coast.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Culver, C., Jackson, M., Davis, J., Vadopalas, B., Bills, M., Olin, P., &amp; CENTER, W. R. A. (2022). Advances in purple-hinge rock scallop culture on the US West Coast. <em>Western Regional Aquaculture Center. United States Department of Agriculture, National Institute of Food and Agriculture</em>.</p>
<p>Gentry, R. R., Froehlich, H. E., Grimm D., Kareiva, P., Parke, M., Rust, M., Gaines, S. D., &amp; Halpern, B. S.(2017). Mapping the global potential for marine aquaculture. <em>Nature ecology &amp; evolution</em>, 1(9), 1317-1324.</p>
<p>Harbo, R. M. (1997). <em>Shells &amp; shellfish of the Pacific northwest: a field guide</em>. Madiera Park, BC: Harbour Publishing.</p>
<p>National Oceanic and Atmospheric Administration. (2024). <em>What is an exclusive economic zone (EEZ)?</em> NOAA Ocean Service. Retrieved December 12, 2025, from https://oceanservice.noaa.gov/facts/eez.html</p>
<p>Schmid, J. (2025). <em>Crassadoma gigantea</em>. Retrieved November 30, 2025, from Reef Species of the World website: https://reeflifesurvey.com/species/crassadoma-gigantea/</p>
<p>University of British Columbia. (2025). Crassadoma gigantea, Giant rock-scallop : fisheries. Retrieved November 30, 2025, from Sealifebase.ca website: https://www.sealifebase.ca/summary/SpeciesSummary.php?id=47314&amp;lang=english</p>
</section>
<section id="data-citations" class="level1">
<h1>Data Citations</h1>
<p><strong>NOAA Sea Surface Temperature (SST)</strong></p>
<p>National Oceanic and Atmospheric Administration (NOAA). 2024. 5km Daily Global Satellite Sea Surface Temperature Anomaly v3.1. Coral Reef Watch Program. Average annual SST rasters for 2008–2012 were used in this analysis. Data files: <code>average_annual_sst_2008.tif</code>, <code>average_annual_sst_2009.tif</code>, <code>average_annual_sst_2010.tif</code>, <code>average_annual_sst_2011.tif</code>, <code>average_annual_sst_2012.tif</code>. Available at: <a href="https://coralreefwatch.noaa.gov/product/5km/"></a></p>
<p><strong>GEBCO Bathymetry</strong></p>
<p>General Bathymetric Chart of the Oceans (GEBCO). 2023. GEBCO Compilation Group: GEBCO 2023 Grid. British Oceanographic Data Centre. Data file: <code>depth.tif</code>. Available at: <a href="https://www.gebco.net/"></a></p>
<p><strong>Exclusive Economic Zones (EEZ)</strong></p>
<p>Flanders Marine Institute (VLIZ). 2023. Maritime Boundaries Geodatabase: Exclusive Economic Zones (EEZ), version 12. MarineRegions.org. Data file: <code>wc_regions_clean.shp</code>. Available at: <a href="https://www.marineregions.org/"></a></p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Evaluating Species-Specific Environmental Suitability for Marine Aquaculture Development Along the U.S. West Coast"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Analysis of U.S. West Coast Exclusive Economic Zones to identify suitable marine aquaculture areas based on species-specific sea surface temperature and depth ranges."</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">  - name: Melannie Moreno Rolón</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">    url: https://mmorenorolon.github.io/</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">    affiliation: Master of Environmental Data Science Program @ The Bren School (UCSB)</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">    affiliation-url: https://ucsb-meds.github.io/</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> last-modified</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [MEDS, R, Geospatial Analysis]</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> "https://cf-images.us-east-1.prod.boltdns.net/v1/static/659677166001/7d188fff-3e5e-4059-b7ef-ffd4be742900/fef50dd1-d58f-4a03-84f7-579058fa9fd7/1280x720/match/image.jpg"</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co">  warnings: false</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co">  results: false</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="an">code-fold:</span><span class="co"> true</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="an">code-tools:</span><span class="co"> true</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="an">editor_options:</span><span class="co"> </span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co">  chunk_output_type: console</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="al">![Aquaculture Image Sourced from NOAA Fisheries](https://cf-images.us-east-1.prod.boltdns.net/v1/static/659677166001/7d188fff-3e5e-4059-b7ef-ffd4be742900/fef50dd1-d58f-4a03-84f7-579058fa9fd7/1280x720/match/image.jpg)</span>{width=450}</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message=FALSE}</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: import-libraries</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="co">#|code-fold: true</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Import libraries</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(testthat)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>As the global population continues to rise, so does the pressure on wild fisheries to meet growing seafood demand. Marine aquaculture offers a promising solution, providing a sustainable alternative that can relieve pressure on wild stocks while supporting economic development. According to Gentry et al. (2017), the availability of suitable ocean space is unlikely to limit the expansion of marine aquaculture, indicating that many regions have the physical capacity to support future growth. This presents an important opportunity for countries such as the United States to develop aquaculture systems that meet both economic and environmental objectives. Thus, the central objective of this project is to identify which areas along the U.S. West Coast meet the environmental conditions necessary to support sustainable aquaculture development.</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>Identifying where aquaculture can be responsibly developed requires evaluating the environmental conditions that support healthy growth and minimize ecological impacts. This project assesses the suitability of West Coast Exclusive Economic Zones (EEZs), defined as marine areas extending up to 200 nautical miles from the U.S. coastline where the United States has jurisdiction over natural resource use (NOAA, 2024), for marine aquaculture using two key environmental constraints: sea surface temperature (SST) and bathymetry. Using satellite-derived SST data from 2008–2012 and a regional bathymetry dataset, the total area within each EEZ that meets species-specific environmental thresholds can be quantified. The analysis focuses on two groups: oysters, which are already widely cultivated in California, and the Purple Hinged Rock Scallop (*Crassadoma gigantea*), a giant scallop species with emerging aquaculture potential (Culver et al., 2022). By integrating spatial environmental data with habitat requirements, this project identifies where conditions are most favorable for expanding sustainable marine aquaculture along the U.S. West Coast.</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a><span class="fu"># Methods</span></span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>To assess aquaculture suitability along the U.S. West Coast, a generalized function was implemented that automates the processing of sea surface temperature (SST), bathymetry, and EEZ boundary data. Depth requirements for the purple-hinged rock scallop (*Crassadoma gigantea*) were obtained from SeaLifeBase, which reports an ecological depth range of 0–80 m below sea level (b.s.l.) (University of British Columbia, 2025; Harbo, 1997). Thermal tolerance data for this species are not provided in SeaLifeBase, so temperature thresholds were derived from Reef Life Survey observations, which indicate a temperature range of approximately 13.3–22.1 degrees Celsius (Schmid, 2025). In addition, suitability thresholds for oysters were incorporated based on published ecological ranges, with optimal SST values between 11–30 degrees Celsius and depth values between 0 and 70 meters b.s.l. These values were used to define species-specific suitability thresholds for reclassification of SST and bathymetry data. The workflow consisted of four phases. </span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Sea Surface Temperature Processing</span></span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>Daily 5-km SST averages from 2008–2012 were compiled and converted into a single long-term mean SST raster. The datasets were first stacked and then averaged by pixel. SST values, originally in Kelvin, were converted to degrees Celsius. </span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE,results='hide'}</span></span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and process SST</span></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>SST_2008 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2008.tif'</span>))</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>SST_2009 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2009.tif'</span>))</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>SST_2010 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2010.tif'</span>))</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>SST_2011 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2011.tif'</span>))</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a>SST_2012 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'average_annual_sst_2012.tif'</span>))</span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that all SST rasters share the same CRS</span></span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">crs</span>(SST_2008) <span class="sc">==</span> <span class="fu">crs</span>(SST_2009) <span class="sc">&amp;</span> </span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a>    <span class="fu">crs</span>(SST_2009) <span class="sc">==</span> <span class="fu">crs</span>(SST_2010) <span class="sc">&amp;</span> </span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a>    <span class="fu">crs</span>(SST_2010) <span class="sc">==</span> <span class="fu">crs</span>(SST_2011)<span class="sc">&amp;</span> </span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a>    <span class="fu">crs</span>(SST_2011) <span class="sc">==</span> <span class="fu">crs</span>(SST_2012)) {</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"All coordinate reference systems match!"</span>)</span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Coordinate reference systems do not match!"</span>)</span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a><span class="co"># Stack SST rasters (2008–2012)</span></span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a>sst_stack <span class="ot">&lt;-</span> <span class="fu">c</span>(SST_2008, SST_2009, SST_2010, SST_2011, SST_2012)</span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that rasters were stacked successfully</span></span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">nlyr</span>(sst_stack) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb10-77"><a href="#cb10-77" aria-hidden="true" tabindex="-1"></a>     <span class="fu">message</span>(<span class="st">"SST stack failed: no raster layers detected."</span>)</span>
<span id="cb10-78"><a href="#cb10-78" aria-hidden="true" tabindex="-1"></a>     <span class="fu">stop</span>(<span class="st">"Halting execution."</span>)</span>
<span id="cb10-79"><a href="#cb10-79" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-80"><a href="#cb10-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-81"><a href="#cb10-81" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute mean SST over time (per pixel)</span></span>
<span id="cb10-82"><a href="#cb10-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-83"><a href="#cb10-83" aria-hidden="true" tabindex="-1"></a>mean_sst <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">mean</span>(sst_stack)</span>
<span id="cb10-84"><a href="#cb10-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-85"><a href="#cb10-85" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert temperature units from Kelvin to Celsius</span></span>
<span id="cb10-86"><a href="#cb10-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-87"><a href="#cb10-87" aria-hidden="true" tabindex="-1"></a>mean_sst_c <span class="ot">&lt;-</span> mean_sst <span class="sc">-</span> <span class="fl">273.15</span></span>
<span id="cb10-88"><a href="#cb10-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-89"><a href="#cb10-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-90"><a href="#cb10-90" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Bathymetry Processing</span></span>
<span id="cb10-91"><a href="#cb10-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-92"><a href="#cb10-92" aria-hidden="true" tabindex="-1"></a>A regional depth raster was reprojected to match the SST coordinate reference system (CRS). The bathymetry was cropped to the spatial extent of the SST data and resampled to its resolution to maintain consistency and cell alignment between rasters. </span>
<span id="cb10-93"><a href="#cb10-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-94"><a href="#cb10-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE,results='hide'}</span></span>
<span id="cb10-95"><a href="#cb10-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare bathymetry (depth) raster</span></span>
<span id="cb10-96"><a href="#cb10-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-97"><a href="#cb10-97" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Load the bathymetry raster</span></span>
<span id="cb10-98"><a href="#cb10-98" aria-hidden="true" tabindex="-1"></a>bathy <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"depth.tif"</span>))</span>
<span id="cb10-99"><a href="#cb10-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-100"><a href="#cb10-100" aria-hidden="true" tabindex="-1"></a><span class="co"># Make CRS match SST:</span></span>
<span id="cb10-101"><a href="#cb10-101" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-102"><a href="#cb10-102" aria-hidden="true" tabindex="-1"></a>bathy_proj <span class="ot">&lt;-</span> <span class="fu">project</span>(bathy, <span class="fu">crs</span>(mean_sst_c))</span>
<span id="cb10-103"><a href="#cb10-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-104"><a href="#cb10-104" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that the re-projection of the depth raster was successful</span></span>
<span id="cb10-105"><a href="#cb10-105" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Bathymetry CRS matches SST CRS after projection"</span>, {</span>
<span id="cb10-106"><a href="#cb10-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_identical</span>(<span class="fu">crs</span>(bathy_proj), <span class="fu">crs</span>(mean_sst_c))</span>
<span id="cb10-107"><a href="#cb10-107" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-108"><a href="#cb10-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-109"><a href="#cb10-109" aria-hidden="true" tabindex="-1"></a><span class="co"># Crop bathymetry to SST's extent</span></span>
<span id="cb10-110"><a href="#cb10-110" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-111"><a href="#cb10-111" aria-hidden="true" tabindex="-1"></a>bathy_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(bathy_proj, mean_sst_c)</span>
<span id="cb10-112"><a href="#cb10-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-113"><a href="#cb10-113" aria-hidden="true" tabindex="-1"></a><span class="co"># Check resolution of depth vs sst data</span></span>
<span id="cb10-114"><a href="#cb10-114" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">xres</span>(bathy_crop) <span class="sc">==</span> <span class="fu">xres</span>(mean_sst_c) <span class="sc">&amp;</span></span>
<span id="cb10-115"><a href="#cb10-115" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">yres</span>(bathy_crop) <span class="sc">==</span> <span class="fu">yres</span>(mean_sst_c))) {</span>
<span id="cb10-116"><a href="#cb10-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"Raster resolutions match!"</span>)</span>
<span id="cb10-117"><a href="#cb10-117" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb10-118"><a href="#cb10-118" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Raster resolutions do not match."</span>)</span>
<span id="cb10-119"><a href="#cb10-119" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-120"><a href="#cb10-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-121"><a href="#cb10-121" aria-hidden="true" tabindex="-1"></a><span class="co"># Resample bathymetry to SST resolution (so each cell lines up):</span></span>
<span id="cb10-122"><a href="#cb10-122" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-123"><a href="#cb10-123" aria-hidden="true" tabindex="-1"></a>depth_res <span class="ot">&lt;-</span> <span class="fu">resample</span>(bathy_crop, mean_sst_c, <span class="at">method =</span> <span class="st">"near"</span>)</span>
<span id="cb10-124"><a href="#cb10-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-125"><a href="#cb10-125" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that the depth and SST match in resolution</span></span>
<span id="cb10-126"><a href="#cb10-126" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Depth raster was resampled to match SST resolution"</span>, {</span>
<span id="cb10-127"><a href="#cb10-127" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_equal</span>(<span class="fu">res</span>(depth_res), <span class="fu">res</span>(mean_sst_c))</span>
<span id="cb10-128"><a href="#cb10-128" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-129"><a href="#cb10-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-130"><a href="#cb10-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-131"><a href="#cb10-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-132"><a href="#cb10-132" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Environmental Suitability Classification</span></span>
<span id="cb10-133"><a href="#cb10-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-134"><a href="#cb10-134" aria-hidden="true" tabindex="-1"></a>Species-specific temperature and depth constraints were translated into binary suitability surfaces. For the purple-hinged rock scallop (*Crassadoma gigantea*), SST values between 13.3–22.1 Celsius and depths between 0–80 meters b.s.l. were classified as suitable (value = 1), with all other values set to unsuitable (value = 0). In contrast, for oysters, suitability was defined by a broader SST range of 11–30 degrees Celsius and shallower depths between 0 and 70 meters b.s.l. Separate binary rasters were generated for each species, and suitability layers were multiplied to produce combined indices identifying locations that simultaneously satisfied both environmental conditions.</span>
<span id="cb10-135"><a href="#cb10-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-136"><a href="#cb10-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE,results='hide'}</span></span>
<span id="cb10-137"><a href="#cb10-137" aria-hidden="true" tabindex="-1"></a><span class="co"># Reclassify SST into suitable / unsuitable</span></span>
<span id="cb10-138"><a href="#cb10-138" aria-hidden="true" tabindex="-1"></a><span class="co"># The oyster thresholds for SST are between 11–30 Celsius</span></span>
<span id="cb10-139"><a href="#cb10-139" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-140"><a href="#cb10-140" aria-hidden="true" tabindex="-1"></a>sst_rcl <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">11</span>,  <span class="dv">0</span>,</span>
<span id="cb10-141"><a href="#cb10-141" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">11</span>, <span class="dv">30</span>,  <span class="dv">1</span>,</span>
<span id="cb10-142"><a href="#cb10-142" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">30</span>, <span class="cn">Inf</span>, <span class="dv">0</span>), <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-143"><a href="#cb10-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-144"><a href="#cb10-144" aria-hidden="true" tabindex="-1"></a>sst_suit <span class="ot">&lt;-</span> <span class="fu">classify</span>(mean_sst_c, <span class="at">rcl =</span> sst_rcl)</span>
<span id="cb10-145"><a href="#cb10-145" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-146"><a href="#cb10-146" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-147"><a href="#cb10-147" aria-hidden="true" tabindex="-1"></a><span class="co"># Reclassify depth into suitable or unsuitable (1, 0)</span></span>
<span id="cb10-148"><a href="#cb10-148" aria-hidden="true" tabindex="-1"></a><span class="co"># The depth thresholds for oysters range is 0-70 meters b.s.l.</span></span>
<span id="cb10-149"><a href="#cb10-149" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-150"><a href="#cb10-150" aria-hidden="true" tabindex="-1"></a>depth_rcl <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="dv">70</span>, <span class="dv">0</span>,</span>
<span id="cb10-151"><a href="#cb10-151" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">-</span><span class="dv">70</span>, <span class="dv">0</span>, <span class="dv">1</span>,</span>
<span id="cb10-152"><a href="#cb10-152" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">0</span>, <span class="cn">Inf</span>, <span class="dv">0</span>), <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-153"><a href="#cb10-153" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-154"><a href="#cb10-154" aria-hidden="true" tabindex="-1"></a>depth_suit <span class="ot">&lt;-</span> <span class="fu">classify</span>(depth_res, depth_rcl)</span>
<span id="cb10-155"><a href="#cb10-155" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-156"><a href="#cb10-156" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine SST and depth suitability</span></span>
<span id="cb10-157"><a href="#cb10-157" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-158"><a href="#cb10-158" aria-hidden="true" tabindex="-1"></a><span class="co"># Unit test for sst and depth CRS</span></span>
<span id="cb10-159"><a href="#cb10-159" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Reclassified rasters share identical CRS"</span>, {</span>
<span id="cb10-160"><a href="#cb10-160" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_identical</span>(<span class="fu">crs</span>(sst_suit), <span class="fu">crs</span>(depth_suit))</span>
<span id="cb10-161"><a href="#cb10-161" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-162"><a href="#cb10-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-163"><a href="#cb10-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiply to get 1 only where both are suitable</span></span>
<span id="cb10-164"><a href="#cb10-164" aria-hidden="true" tabindex="-1"></a>suitability <span class="ot">&lt;-</span> sst_suit <span class="sc">*</span> depth_suit <span class="co"># 1 = suitable, 0 = unsuitable</span></span>
<span id="cb10-165"><a href="#cb10-165" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-166"><a href="#cb10-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-167"><a href="#cb10-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-168"><a href="#cb10-168" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Suitability Estimation at the EEZ Level</span></span>
<span id="cb10-169"><a href="#cb10-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-170"><a href="#cb10-170" aria-hidden="true" tabindex="-1"></a>Exclusive Economic Zone (EEZ) boundaries were transformed to match the SST projection. The combined suitability raster was masked to the extent of each EEZ, and the area of each raster cell was computed in square kilometers. Suitable cell areas were aggregated within each EEZ to obtain total suitable area per region. These results were subsequently merged with the EEZ polygon dataset and visualized using a colorblind-friendly continuous color scale.</span>
<span id="cb10-171"><a href="#cb10-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-172"><a href="#cb10-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE,results='hide'}</span></span>
<span id="cb10-173"><a href="#cb10-173" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare EEZ vector and mask</span></span>
<span id="cb10-174"><a href="#cb10-174" aria-hidden="true" tabindex="-1"></a>eez_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"wc_regions_clean.shp"</span>), <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-175"><a href="#cb10-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-176"><a href="#cb10-176" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to SpatVector format</span></span>
<span id="cb10-177"><a href="#cb10-177" aria-hidden="true" tabindex="-1"></a>eez <span class="ot">&lt;-</span> <span class="fu">vect</span>(eez_sf)</span>
<span id="cb10-178"><a href="#cb10-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-179"><a href="#cb10-179" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-project with mean sst's CRS</span></span>
<span id="cb10-180"><a href="#cb10-180" aria-hidden="true" tabindex="-1"></a>eez_proj <span class="ot">&lt;-</span> <span class="fu">project</span>(eez, mean_sst_c)</span>
<span id="cb10-181"><a href="#cb10-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-182"><a href="#cb10-182" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that the re-projection of the EEZ shapefile was successful</span></span>
<span id="cb10-183"><a href="#cb10-183" aria-hidden="true" tabindex="-1"></a><span class="fu">test_that</span>(<span class="st">"Bathymetry CRS matches SST CRS after projection"</span>, {</span>
<span id="cb10-184"><a href="#cb10-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expect_identical</span>(<span class="fu">crs</span>(eez_proj), <span class="fu">crs</span>(mean_sst_c))</span>
<span id="cb10-185"><a href="#cb10-185" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb10-186"><a href="#cb10-186" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-187"><a href="#cb10-187" aria-hidden="true" tabindex="-1"></a><span class="co"># Mask suitability by EEZ</span></span>
<span id="cb10-188"><a href="#cb10-188" aria-hidden="true" tabindex="-1"></a>suitability_eez <span class="ot">&lt;-</span> <span class="fu">mask</span>(suitability, eez_proj)</span>
<span id="cb10-189"><a href="#cb10-189" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-190"><a href="#cb10-190" aria-hidden="true" tabindex="-1"></a><span class="co"># Count suitable cells per EEZ</span></span>
<span id="cb10-191"><a href="#cb10-191" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-192"><a href="#cb10-192" aria-hidden="true" tabindex="-1"></a><span class="co"># a. Compute area in squared kilometers of each raster cell</span></span>
<span id="cb10-193"><a href="#cb10-193" aria-hidden="true" tabindex="-1"></a>cell_area_km <span class="ot">&lt;-</span> <span class="fu">cellSize</span>(suitability_eez, <span class="at">unit =</span> <span class="st">"km"</span>)</span>
<span id="cb10-194"><a href="#cb10-194" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-195"><a href="#cb10-195" aria-hidden="true" tabindex="-1"></a><span class="co"># b. Multiply suitability (0/1) by area to get "suitable area per cell"</span></span>
<span id="cb10-196"><a href="#cb10-196" aria-hidden="true" tabindex="-1"></a>suitable_area_raster <span class="ot">&lt;-</span> suitability_eez <span class="sc">*</span> cell_area_km</span>
<span id="cb10-197"><a href="#cb10-197" aria-hidden="true" tabindex="-1"></a><span class="co"># Cells that were 1 now contain area in km²</span></span>
<span id="cb10-198"><a href="#cb10-198" aria-hidden="true" tabindex="-1"></a><span class="co"># Cells that were 0 remain 0</span></span>
<span id="cb10-199"><a href="#cb10-199" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-200"><a href="#cb10-200" aria-hidden="true" tabindex="-1"></a><span class="co"># c. Extract total suitable area (km²) for each EEZ polygon</span></span>
<span id="cb10-201"><a href="#cb10-201" aria-hidden="true" tabindex="-1"></a>eez_suitable_area <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extract</span>(suitable_area_raster, </span>
<span id="cb10-202"><a href="#cb10-202" aria-hidden="true" tabindex="-1"></a>                             eez_proj,</span>
<span id="cb10-203"><a href="#cb10-203" aria-hidden="true" tabindex="-1"></a>                             <span class="at">fun =</span> sum,</span>
<span id="cb10-204"><a href="#cb10-204" aria-hidden="true" tabindex="-1"></a>                             <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-205"><a href="#cb10-205" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-206"><a href="#cb10-206" aria-hidden="true" tabindex="-1"></a><span class="co"># d. Add the EEZ region names to the output</span></span>
<span id="cb10-207"><a href="#cb10-207" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace "region" with the correct column name from your EEZ shapefile</span></span>
<span id="cb10-208"><a href="#cb10-208" aria-hidden="true" tabindex="-1"></a>eez_suitable_area<span class="sc">$</span>region <span class="ot">&lt;-</span> eez_proj<span class="sc">$</span>rgn</span>
<span id="cb10-209"><a href="#cb10-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-210"><a href="#cb10-210" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the "mean"column</span></span>
<span id="cb10-211"><a href="#cb10-211" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(eez_suitable_area)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"suitable_km2"</span></span>
<span id="cb10-212"><a href="#cb10-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-213"><a href="#cb10-213" aria-hidden="true" tabindex="-1"></a><span class="co"># Format the table for EEZ suitable area totals</span></span>
<span id="cb10-214"><a href="#cb10-214" aria-hidden="true" tabindex="-1"></a>eez_suitable_area_table <span class="ot">&lt;-</span> eez_suitable_area <span class="sc">%&gt;%</span></span>
<span id="cb10-215"><a href="#cb10-215" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(region, suitable_km2) <span class="sc">%&gt;%</span></span>
<span id="cb10-216"><a href="#cb10-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"EEZ Region"</span>, <span class="st">"Suitable Area (km²)"</span>),</span>
<span id="cb10-217"><a href="#cb10-217" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"Total Suitable Area by EEZ Region"</span>,</span>
<span id="cb10-218"><a href="#cb10-218" aria-hidden="true" tabindex="-1"></a>        <span class="at">align =</span> <span class="st">"lr"</span>, <span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-219"><a href="#cb10-219" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(</span>
<span id="cb10-220"><a href="#cb10-220" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb10-221"><a href="#cb10-221" aria-hidden="true" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span>
<span id="cb10-222"><a href="#cb10-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-223"><a href="#cb10-223" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge table back into EEZ SpatVector</span></span>
<span id="cb10-224"><a href="#cb10-224" aria-hidden="true" tabindex="-1"></a>eez_map <span class="ot">&lt;-</span> eez_proj</span>
<span id="cb10-225"><a href="#cb10-225" aria-hidden="true" tabindex="-1"></a>eez_map<span class="sc">$</span>suitable_km2 <span class="ot">&lt;-</span> eez_suitable_area<span class="sc">$</span>suitable_km2</span>
<span id="cb10-226"><a href="#cb10-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-227"><a href="#cb10-227" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the final map</span></span>
<span id="cb10-228"><a href="#cb10-228" aria-hidden="true" tabindex="-1"></a>map_final <span class="ot">&lt;-</span> <span class="fu">tm_basemap</span>(<span class="st">"Esri.OceanBasemap"</span>) <span class="sc">+</span></span>
<span id="cb10-229"><a href="#cb10-229" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-230"><a href="#cb10-230" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(eez_map) <span class="sc">+</span></span>
<span id="cb10-231"><a href="#cb10-231" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-232"><a href="#cb10-232" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"suitable_km2"</span>, </span>
<span id="cb10-233"><a href="#cb10-233" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">values =</span> <span class="st">"brewer.blues"</span>, </span>
<span id="cb10-234"><a href="#cb10-234" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">style =</span> <span class="st">"quantile"</span>),</span>
<span id="cb10-235"><a href="#cb10-235" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">bg.color =</span> <span class="st">"white"</span>,</span>
<span id="cb10-236"><a href="#cb10-236" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">bg.alpha =</span> <span class="fl">0.2</span>,</span>
<span id="cb10-237"><a href="#cb10-237" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">title =</span> <span class="st">"Suitable Area (km²)"</span>,</span>
<span id="cb10-238"><a href="#cb10-238" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb10-239"><a href="#cb10-239" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"right"</span>, <span class="st">"top"</span>)),</span>
<span id="cb10-240"><a href="#cb10-240" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb10-241"><a href="#cb10-241" aria-hidden="true" tabindex="-1"></a>              <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb10-242"><a href="#cb10-242" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-243"><a href="#cb10-243" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"rgn"</span>, <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb10-244"><a href="#cb10-244" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb10-245"><a href="#cb10-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb10-246"><a href="#cb10-246" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="st">"Suitable Area for Oyster Aquaculture in West Coast EEZ"</span>) <span class="sc">+</span></span>
<span id="cb10-247"><a href="#cb10-247" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-248"><a href="#cb10-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">TRUE</span>, <span class="at">frame.lwd =</span> <span class="fl">0.4</span>, <span class="at">frame.r =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb10-249"><a href="#cb10-249" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-250"><a href="#cb10-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scalebar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">250</span>, <span class="dv">500</span>), </span>
<span id="cb10-251"><a href="#cb10-251" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>)) <span class="sc">+</span></span>
<span id="cb10-252"><a href="#cb10-252" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-253"><a href="#cb10-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">"arrow"</span>, <span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"left"</span>, <span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb10-254"><a href="#cb10-254" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-255"><a href="#cb10-255" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tmap_options</span>(<span class="at">component.autoscale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-256"><a href="#cb10-256" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-257"><a href="#cb10-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-258"><a href="#cb10-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-259"><a href="#cb10-259" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Analysis</span></span>
<span id="cb10-260"><a href="#cb10-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-261"><a href="#cb10-261" aria-hidden="true" tabindex="-1"></a>The workflow was first applied to oysters to demonstrate the processing steps before generalizing the approach. To avoid repeating the oyster workflow for each species, we implemented a generalized function that accepts species-specific parameters.</span>
<span id="cb10-262"><a href="#cb10-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-263"><a href="#cb10-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=TRUE,results='hide'}</span></span>
<span id="cb10-264"><a href="#cb10-264" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: oyster-function</span></span>
<span id="cb10-265"><a href="#cb10-265" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"R"</span>,<span class="st">"suitability_function.R"</span>)) </span>
<span id="cb10-266"><a href="#cb10-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-267"><a href="#cb10-267" aria-hidden="true" tabindex="-1"></a>oyster_results <span class="ot">&lt;-</span> <span class="fu">map_suitability</span>(<span class="at">tmin =</span> <span class="dv">11</span>, <span class="at">tmax =</span> <span class="dv">30</span>,</span>
<span id="cb10-268"><a href="#cb10-268" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">dmin =</span> <span class="sc">-</span><span class="dv">70</span>, <span class="at">dmax =</span> <span class="dv">0</span>,</span>
<span id="cb10-269"><a href="#cb10-269" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">species_name =</span> <span class="st">"Oysters"</span>)</span>
<span id="cb10-270"><a href="#cb10-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-271"><a href="#cb10-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-272"><a href="#cb10-272" aria-hidden="true" tabindex="-1"></a>We then tested the function with scallop parameters to confirm that the function can be applied to any species of interest and their ecological parameters.</span>
<span id="cb10-273"><a href="#cb10-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-274"><a href="#cb10-274" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE, results='hide'}</span></span>
<span id="cb10-275"><a href="#cb10-275" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: scallop-function</span></span>
<span id="cb10-276"><a href="#cb10-276" aria-hidden="true" tabindex="-1"></a>scallop_results <span class="ot">&lt;-</span> <span class="fu">map_suitability</span>(<span class="at">tmin =</span> <span class="fl">13.3</span>, <span class="at">tmax =</span> <span class="fl">22.1</span>,</span>
<span id="cb10-277"><a href="#cb10-277" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dmin =</span> <span class="sc">-</span><span class="dv">80</span>, <span class="at">dmax =</span> <span class="dv">0</span>,</span>
<span id="cb10-278"><a href="#cb10-278" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">species_name =</span> <span class="st">"Purple-Hinged Rock Scallops"</span>)</span>
<span id="cb10-279"><a href="#cb10-279" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-280"><a href="#cb10-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-281"><a href="#cb10-281" aria-hidden="true" tabindex="-1"></a><span class="fu"># Results </span></span>
<span id="cb10-282"><a href="#cb10-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-283"><a href="#cb10-283" aria-hidden="true" tabindex="-1"></a>The resulting suitability maps and EEZ-level summaries for oysters and scallops are shown below. </span>
<span id="cb10-284"><a href="#cb10-284" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=FALSE,message=FALSE}</span></span>
<span id="cb10-285"><a href="#cb10-285" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: map-oysters</span></span>
<span id="cb10-286"><a href="#cb10-286" aria-hidden="true" tabindex="-1"></a><span class="co"># Display oyster map</span></span>
<span id="cb10-287"><a href="#cb10-287" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(<span class="at">tm =</span> oyster_results<span class="sc">$</span>map, <span class="fu">here</span>(<span class="st">"figures"</span>,<span class="st">"oyster_map.png"</span>),</span>
<span id="cb10-288"><a href="#cb10-288" aria-hidden="true" tabindex="-1"></a>          <span class="at">width =</span> <span class="dv">6</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">units =</span> <span class="st">"in"</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb10-289"><a href="#cb10-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-290"><a href="#cb10-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-291"><a href="#cb10-291" aria-hidden="true" tabindex="-1"></a><span class="fu">## Oyster Aquaculture Suitability</span></span>
<span id="cb10-292"><a href="#cb10-292" aria-hidden="true" tabindex="-1"></a><span class="al">![](/figures/oyster_map.png)</span></span>
<span id="cb10-293"><a href="#cb10-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-294"><a href="#cb10-294" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=FALSE,message=FALSE}</span></span>
<span id="cb10-295"><a href="#cb10-295" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: map-scallops</span></span>
<span id="cb10-296"><a href="#cb10-296" aria-hidden="true" tabindex="-1"></a><span class="co"># Display scallop map</span></span>
<span id="cb10-297"><a href="#cb10-297" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(<span class="at">tm =</span> scallop_results<span class="sc">$</span>map, <span class="fu">here</span>(<span class="st">"figures"</span>,<span class="st">"scallop_map.png"</span>),</span>
<span id="cb10-298"><a href="#cb10-298" aria-hidden="true" tabindex="-1"></a>          <span class="at">width =</span> <span class="dv">6</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">units =</span> <span class="st">"in"</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb10-299"><a href="#cb10-299" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-300"><a href="#cb10-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-301"><a href="#cb10-301" aria-hidden="true" tabindex="-1"></a><span class="fu">## Scallop Aquaculture Suitability</span></span>
<span id="cb10-302"><a href="#cb10-302" aria-hidden="true" tabindex="-1"></a><span class="al">![](/figures/scallop_map.png)</span></span>
<span id="cb10-303"><a href="#cb10-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-304"><a href="#cb10-304" aria-hidden="true" tabindex="-1"></a><span class="fu">## EEZ-Level Suitable Area Summary</span></span>
<span id="cb10-305"><a href="#cb10-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-306"><a href="#cb10-306" aria-hidden="true" tabindex="-1"></a>To support comparisons across regions, the total environmentally suitable area for aquaculture within each West Coast Exclusive Economic Zone (EEZ) is summarized in the figures below. These tables quantify how much space within each EEZ meets species-specific temperature and depth thresholds. With these metrics, aquaculture potential across regions and between species was compared.</span>
<span id="cb10-307"><a href="#cb10-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-308"><a href="#cb10-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=FALSE,message=FALSE}</span></span>
<span id="cb10-309"><a href="#cb10-309" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: summary tables</span></span>
<span id="cb10-310"><a href="#cb10-310" aria-hidden="true" tabindex="-1"></a><span class="co"># Display EEZ summary tables</span></span>
<span id="cb10-311"><a href="#cb10-311" aria-hidden="true" tabindex="-1"></a>oyster_results<span class="sc">$</span>table</span>
<span id="cb10-312"><a href="#cb10-312" aria-hidden="true" tabindex="-1"></a>scallop_results<span class="sc">$</span>table</span>
<span id="cb10-313"><a href="#cb10-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-314"><a href="#cb10-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-315"><a href="#cb10-315" aria-hidden="true" tabindex="-1"></a>The analysis identified stark differences in the amount of environmentally suitable area for aquaculture across West Coast EEZ regions. For oysters, Central California and Southern California contained the largest suitable areas, with approximately 4,070 squared km and 3,757 squared km respectively, followed by Washington (2,378 squared km) and Oregon (1,074 squared km). Northern California showed a more limited suitable habitat (178 squared km). In contrast, suitable areas for purple-hinged rock scallops were highly concentrated in the southern portion of the study region. Southern California accounted for nearly all suitable habitat (3,567 squared km), with a small area in Central California (119 km²), while Oregon, Washington, and Northern California contained no suitable area based on the species’ temperature and depth thresholds.</span>
<span id="cb10-316"><a href="#cb10-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-317"><a href="#cb10-317" aria-hidden="true" tabindex="-1"></a><span class="fu"># Discussion</span></span>
<span id="cb10-318"><a href="#cb10-318" aria-hidden="true" tabindex="-1"></a>The results directly address the project objective of identifying where environmental conditions along the U.S. West Coast support sustainable marine aquaculture development. The spatial differences in aquaculture suitability among oysters and scallops reflect how environmental constraints, namely sea surface temperature and bathymetry, shape the feasibility of expanding aquaculture across Exclusive Economic Zones (EEZs). </span>
<span id="cb10-319"><a href="#cb10-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-320"><a href="#cb10-320" aria-hidden="true" tabindex="-1"></a>Oyster suitability was broadly distributed across the West Coast, with the greatest concentrations being in Central and Southern California. These regions offer both the depth and thermal ranges that align with oyster tolerance, which resulted in several thousand square kilometers of potentially viable habitat. Washington and Oregon also contained meaningful amounts of suitable area, although to a lesser extent. The distribution pattern suggests that oyster aquaculture has relatively flexible environmental requirements within this coastline. This widespread distribution supports prior findings that physical ocean space is unlikely to limit aquaculture expansion (Gentry et al., 2017) and suggests that oysters represent a species with strong potential to contribute to meeting growing seafood demand while alleviating pressure on wild fisheries.</span>
<span id="cb10-321"><a href="#cb10-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-322"><a href="#cb10-322" aria-hidden="true" tabindex="-1"></a>In contrast, the distribution of suitable habitat for purple-hinged rock scallops was highly geographically restricted. Southern California dominated the available area, as it contributed to nearly all suitable habitat identified in the study, with only a small area in Central California meeting threshold conditions. The absence of suitable areas in Oregon, Washington, and Northern California indicates that the species’ temperature range limits its potential along the cooler northern waters. These results align with the species’ known geographic distribution, as purple-hinged rock scallops are more frequently associated with subtidal, subtropical environments (Culver et al., 2022).</span>
<span id="cb10-323"><a href="#cb10-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-324"><a href="#cb10-324" aria-hidden="true" tabindex="-1"></a>The stark contrast between the two species underscores the importance of evaluating on a species-specific level and considering their environmental thresholds when evaluating aquaculture potential. While oysters exhibit broad tolerance across the West Coast that enables aquaculture development across multiple EEZs, the purple-hinged rock scallop is limited to a much smaller geographic range despite being native to the region. From a planning perspective, this means that opportunities to expand scallop aquaculture are highly geographically concentrated, while oyster aquaculture can be distributed more widely. Further research is needed to translate these metrics into practical site selection, like evaluating regulatory conditions, ecological interactions, and infrastructure considerations. Nonetheless, by identifying where environmental conditions are most favorable, this study provides a necessary first step toward supporting sustainable marine aquaculture development along the U.S. West Coast.</span>
<span id="cb10-325"><a href="#cb10-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-326"><a href="#cb10-326" aria-hidden="true" tabindex="-1"></a><span class="fu"># References</span></span>
<span id="cb10-327"><a href="#cb10-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-328"><a href="#cb10-328" aria-hidden="true" tabindex="-1"></a>Culver, C., Jackson, M., Davis, J., Vadopalas, B., Bills, M., Olin, P., &amp; CENTER, W. R. A. (2022). Advances in purple-hinge rock scallop culture on the US West Coast. *Western Regional Aquaculture Center. United States Department of Agriculture, National Institute of Food and Agriculture*.</span>
<span id="cb10-329"><a href="#cb10-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-330"><a href="#cb10-330" aria-hidden="true" tabindex="-1"></a>Gentry, R. R., Froehlich, H. E., Grimm D., Kareiva, P., Parke, M., Rust, M., Gaines, S. D., &amp;  Halpern, B. S.(2017). Mapping the global potential for marine aquaculture. *Nature ecology &amp; evolution*, 1(9), 1317-1324.</span>
<span id="cb10-331"><a href="#cb10-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-332"><a href="#cb10-332" aria-hidden="true" tabindex="-1"></a>Harbo, R. M. (1997). *Shells &amp; shellfish of the Pacific northwest: a field guide*. Madiera Park, BC: Harbour Publishing.</span>
<span id="cb10-333"><a href="#cb10-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-334"><a href="#cb10-334" aria-hidden="true" tabindex="-1"></a>National Oceanic and Atmospheric Administration. (2024). *What is an exclusive economic zone (EEZ)?* NOAA Ocean Service. Retrieved December 12, 2025, from https://oceanservice.noaa.gov/facts/eez.html</span>
<span id="cb10-335"><a href="#cb10-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-336"><a href="#cb10-336" aria-hidden="true" tabindex="-1"></a>Schmid, J. (2025). *Crassadoma gigantea*. Retrieved November 30, 2025, from Reef Species of the World website: https://reeflifesurvey.com/species/crassadoma-gigantea/</span>
<span id="cb10-337"><a href="#cb10-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-338"><a href="#cb10-338" aria-hidden="true" tabindex="-1"></a>University of British Columbia. (2025). Crassadoma gigantea,  Giant rock-scallop  : fisheries. Retrieved November 30, 2025, from Sealifebase.ca website: https://www.sealifebase.ca/summary/SpeciesSummary.php?id=47314&amp;lang=english</span>
<span id="cb10-339"><a href="#cb10-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-340"><a href="#cb10-340" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Citations</span></span>
<span id="cb10-341"><a href="#cb10-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-342"><a href="#cb10-342" aria-hidden="true" tabindex="-1"></a>**NOAA Sea Surface Temperature (SST)**</span>
<span id="cb10-343"><a href="#cb10-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-344"><a href="#cb10-344" aria-hidden="true" tabindex="-1"></a>National Oceanic and Atmospheric Administration (NOAA). 2024. 5km Daily Global Satellite Sea Surface Temperature Anomaly v3.1. Coral Reef Watch Program. Average annual SST rasters for 2008–2012 were used in this analysis.</span>
<span id="cb10-345"><a href="#cb10-345" aria-hidden="true" tabindex="-1"></a>Data files: <span class="in">`average_annual_sst_2008.tif`</span>, <span class="in">`average_annual_sst_2009.tif`</span>, <span class="in">`average_annual_sst_2010.tif`</span>, <span class="in">`average_annual_sst_2011.tif`</span>, <span class="in">`average_annual_sst_2012.tif`</span>.</span>
<span id="cb10-346"><a href="#cb10-346" aria-hidden="true" tabindex="-1"></a>Available at: [](https://coralreefwatch.noaa.gov/product/5km/)</span>
<span id="cb10-347"><a href="#cb10-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-348"><a href="#cb10-348" aria-hidden="true" tabindex="-1"></a>**GEBCO Bathymetry**</span>
<span id="cb10-349"><a href="#cb10-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-350"><a href="#cb10-350" aria-hidden="true" tabindex="-1"></a>General Bathymetric Chart of the Oceans (GEBCO). 2023. GEBCO Compilation Group: GEBCO 2023 Grid. British Oceanographic Data Centre.</span>
<span id="cb10-351"><a href="#cb10-351" aria-hidden="true" tabindex="-1"></a>Data file: <span class="in">`depth.tif`</span>.</span>
<span id="cb10-352"><a href="#cb10-352" aria-hidden="true" tabindex="-1"></a>Available at: [](https://www.gebco.net/)</span>
<span id="cb10-353"><a href="#cb10-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-354"><a href="#cb10-354" aria-hidden="true" tabindex="-1"></a>**Exclusive Economic Zones (EEZ)**</span>
<span id="cb10-355"><a href="#cb10-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-356"><a href="#cb10-356" aria-hidden="true" tabindex="-1"></a>Flanders Marine Institute (VLIZ). 2023. Maritime Boundaries Geodatabase: Exclusive Economic Zones (EEZ), version 12. MarineRegions.org.</span>
<span id="cb10-357"><a href="#cb10-357" aria-hidden="true" tabindex="-1"></a>Data file: <span class="in">`wc_regions_clean.shp`</span>.</span>
<span id="cb10-358"><a href="#cb10-358" aria-hidden="true" tabindex="-1"></a>Available at: [](https://www.marineregions.org/)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Melannie Moreno Rolón</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../posts.html">
<p>Posts</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>